/*
 * Copyright (c) 2018 Andret Tools System. Copying and modifying allowed only keeping git link reference.
 */

plugins {
	id 'com.github.johnrengelman.shadow' version '7.1.2'
	id 'kr.entree.spigradle' version '2.4.2'
}

apply plugin: 'idea'
apply plugin: 'java'

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

repositories {
	mavenCentral()
	mavenLocal()
	spigot()
}

dependencies {
	compileOnly group: 'org.jetbrains', name: 'annotations', version: '24.0.1'
	compileOnly group: 'org.spigotmc', name: 'spigot-api', version: '1.19.2-R0.1-SNAPSHOT'
	implementation rootProject
}

compileJava.options.compilerArgs << '-parameters' << '-g' << '-Xlint:deprecation' << '-Xlint:unchecked'

shadowJar {
	dependencies {
		rootProject
	}
}

jar {
	dependsOn shadowJar
}

spigot {
	authors = ['Andret']
	apiVersion = '1.17'
	libraries = ['org.jetbrains:annotations:24.0.1']

	commands {
		test {
			description = 'The main command.'
			usage = '/<command>'
		}
		parameters {
			description = 'Parameters command.'
			usage = '/<command>'
		}
	}
}
