buildscript {
	repositories {
		jcenter()
		maven { url "https://plugins.gradle.org/m2/" }
	}
	dependencies {
		classpath 'com.github.jengelman.gradle.plugins:shadow:2.0.1'
	}
}

plugins {
	id "com.github.johnrengelman.shadow" version "5.2.0"
	id 'kr.entree.spigradle' version "1.2.1"
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'com.github.johnrengelman.shadow'

group = pluginGroup
version = pluginVersion

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

repositories {
	mavenCentral()
	mavenLocal()
	spigot()
}

dependencies {
	implementation rootProject
	compileOnly 'org.spigotmc:spigot-api:1.15.1-R0.1-SNAPSHOT'
}

shadowJar {
	dependencies {
		rootProject
	}
}

tasks.withType(JavaCompile) {
	options.compilerArgs << '-Xlint:unchecked' << '-parameters' << '-g'
	options.deprecation = true
}

build.dependsOn(shadowJar)

spigot {
	authors = ['Andret']
	apiVersion = '1.15'

	commands {
		test {
			description = 'The main Help command.'
			usage = '/<command>'
		}
	}
}
