#
# Copyright (c) 2018 Andret Tools System. Copying and modifying allowed only keeping git link reference.
#
image: gradle:7.6-jdk11

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod a+x gradlew

stages:
  - build
  - verify
  - deploy

compile:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/classes/**
      - build/libs/*.jar

testng:
  stage: verify
  script:
    - ./gradlew test
  coverage: '/    - Instruction Coverage: ([0-9.]+)%/'
  artifacts:
    reports:
      junit: build/test-results/test/**.xml

integration:
  stage: verify
  script:
    - ./gradlew integrationTest

checkstyle:
  stage: verify
  script:
    - ./gradlew checkstyleMain

publish:
  stage: deploy
  script:
    - ./gradlew clean
    - ./gradlew publish
  only:
    - master
  when: manual

pages:
  stage: deploy
  script:
    - ./gradlew javadoc
  after_script:
    - mv build/docs/javadoc/ public/
  artifacts:
    paths:
      - public/**
  only:
    - master
  when: manual
