image: gradle:jdk11

stages:
  - prepare
  - test
  - deploy

compile:
  stage: prepare
  script:
    - gradle compileJava
  artifacts:
    paths:
      - build/classes/**

delombok:
  stage: prepare
  script:
    - gradle delombok
  artifacts:
    paths:
      - build/delombok/**

junit:
  stage: test
  dependencies:
    - compile
  script:
    - gradle test printCoverage
  coverage: '/^Coverage:\s(\d+\.\d+%)/'
  when: on_success
  artifacts:
    paths:
      - build/reports/jacoco/
    reports:
      junit: build/test-results/test/**.xml

publish:
  stage: deploy
  script:
    - gradle clean
    - gradle publish
  only:
    - master
  when: manual

javadoc:
  stage: deploy
  script:
    - gradle javadoc
    - mv build/docs/javadoc/ public/
  artifacts:
    paths:
      - public
  only:
    - master
