/*
 * Copyright Andret (c) 2019. Copying and modifying allowed only keeping git link reference.
 */
buildscript {
	repositories {
		jcenter()
		maven {
			url "https://plugins.gradle.org/m2/"
		}
	}
	dependencies {
		classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.9.6"
	}
}

plugins {
	id 'java-library'
	id 'maven-publish'
	id 'java'
}

apply plugin: 'com.jfrog.artifactory'
apply plugin: 'maven-publish'

group 'eu.andret'
version '0.0.2-alpha-internal-5'

sourceCompatibility = 1.8

repositories {
	mavenCentral()
	maven {
		url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
	}
	maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
}

dependencies {
	compileOnly group: 'org.spigotmc', name: 'spigot-api', version: '1.13.2-R0.1-SNAPSHOT'
	compileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.2'
	annotationProcessor group: 'org.projectlombok', name: 'lombok', version: '1.18.2'
	testCompile group: 'junit', name: 'junit', version: '4.12'
}

compileJava.options.compilerArgs << '-parameters' << '-g'

javadoc {
	source = sourceSets.main.allJava
	classpath = configurations.compileClasspath

	options {
		setMemberLevel JavadocMemberLevel.PUBLIC
		setAuthor true

		links "https://docs.oracle.com/javase/8/docs/api/"
	}
}

task sourceJar(type: Jar) {
	classifier 'sources'
	from sourceSets.main.allJava
}

task packageJavadoc(type: Jar) {
	classifier 'javadoc'
	from javadoc
}

publishing {
	artifactoryPublish.dependsOn('build')
	publications {
		lib(MavenPublication) {
			groupId = project.group
			version = project.version
			artifactId = 'ats-arguments'

			artifact "${project.buildDir}/libs/${artifactId}-${project.version}.jar"
			artifact sourceJar
			artifact packageJavadoc

			pom.withXml {
				def dependenciesNode = asNode().appendNode("dependencies")

				configurations.implementation.allDependencies.each {
					def dependencyNode = dependenciesNode.appendNode('dependency')
					dependencyNode.appendNode('groupId', it.group)
					dependencyNode.appendNode('artifactId', it.name)
					dependencyNode.appendNode('version', it.version)
				}
			}
		}
	}
}

artifactory {
	contextUrl = 'https://repo.andret.eu/'

	publish {
		repository {
			repoKey = 'andret-tools-system'
			if (project.hasProperty('username') && project.hasProperty('username')) {
				username = project.property('username')
				password = project.property('password')
			} else {
				print 'No credentials'
			}
		}
		defaults {
			publishArtifacts = true
			publishPom = true
		}
	}
}

artifactoryPublish {
	publications(publishing.publications.lib)
}
