/*
 * Copyright Andret (c) 2018-2021. Copying and modifying allowed only keeping git link reference.
 */
import io.franzbecker.gradle.lombok.task.DelombokTask

plugins {
	id 'io.franzbecker.gradle-lombok' version '5.0.0'
	id 'de.jansauer.printcoverage' version '2.0.0'
}

apply plugin: 'idea'
apply plugin: 'java'
apply plugin: 'jacoco'
apply plugin: 'maven-publish'
apply plugin: 'checkstyle'

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

sourceSets {
	integration {
		java.srcDir "$projectDir/src/integration/java"
		resources.srcDir "$projectDir/src/integration/resources"
		compileClasspath += main.output + test.output
		runtimeClasspath += main.output + test.output
	}
}

configurations {
	integrationImplementation.extendsFrom testImplementation
	integrationImplementation.canBeResolved true
	integrationRuntimeOnly.extendsFrom testRuntimeOnly
	integrationRuntimeOnly.canBeResolved true
}

task integrationTest(type: Test) {
	description = 'Runs the integration tests.'
	group = 'verification'
	testClassesDirs = sourceSets.integration.output.classesDirs
	classpath = sourceSets.integration.runtimeClasspath
	outputs.upToDateWhen { false }
	useJUnitPlatform()
}

idea {
	module {
		testSourceDirs += sourceSets.integration.java.srcDirs
		testResourceDirs += sourceSets.integration.resources.srcDirs
	}
}

check.dependsOn integrationTest

repositories {
	mavenCentral()
	maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
}

dependencies {
	compileOnly group: 'org.spigotmc', name: 'spigot-api', version: '1.19.2-R0.1-SNAPSHOT'
	compileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.24'
	compileOnly group: 'org.jetbrains', name: 'annotations', version: '23.0.0'
	implementation group: 'org.jetbrains', name: 'annotations', version: '23.0.0'
	annotationProcessor group: 'org.projectlombok', name: 'lombok', version: '1.18.24'

	testCompileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.24'
	testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.8.2'
	testImplementation group: 'org.spigotmc', name: 'spigot-api', version: '1.19.2-R0.1-SNAPSHOT'
	testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.8.2'
	testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-params', version: '5.8.2'
	testImplementation group: 'org.mockito', name: 'mockito-core', version: '3.4.6'
	testImplementation group: 'org.mockito', name: 'mockito-junit-jupiter', version: '3.4.6'
	testImplementation group: 'org.mockito', name: 'mockito-inline', version: '3.4.6'
	testAnnotationProcessor group: 'org.projectlombok', name: 'lombok', version: '1.18.24'
}

compileJava.options.compilerArgs << '-parameters' << '-g' << '-Xlint:deprecation' << '-Xlint:unchecked'
compileTestJava.options.compilerArgs << '-parameters' << '-g' << '-Xlint:deprecation' << '-Xlint:unchecked'

checkstyleMain.exclude('example/**.java')
checkstyleTest.exclude('**')
checkstyleIntegration.exclude("**")

test {
	useJUnitPlatform()
	finalizedBy jacocoTestCoverageVerification, printCoverage
}

jacocoTestReport {
	reports.xml.enabled true
	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, exclude: ['example/**'])
		}))
	}
}

jacocoTestCoverageVerification {
	violationRules {
		rule {
			limit {
				minimum = 1.0
			}
			excludes = ['example*', 'eu.andret.arguments.example.*']
		}
	}
}

javadoc {
	source = sourceSets.main.allJava
	classpath = configurations.compileClasspath

	options {
		setMemberLevel JavadocMemberLevel.PUBLIC
		setAuthor true

		links 'https://docs.oracle.com/en/java/javase/11/docs/api/'
	}
}

task sourceJar(type: Jar) {
	archiveClassifier.set('sources')
	from sourceSets.main.allJava
}

task packageJavadoc(type: Jar) {
	archiveClassifier.set('javadoc')
	from javadoc
}

publishing {
	publications {
		//noinspection GroovyAssignabilityCheck
		library(MavenPublication) {
			from components.java
			artifact tasks.sourceJar
			artifact tasks.packageJavadoc
			groupId = project.group
			version = project.version
			artifactId = project.codeName
		}
	}
	repositories {
		maven {
			url 'https://gitlab.com/api/v4/projects/12063927/packages/maven'
			credentials(HttpHeaderCredentials) {
				name = 'Job-Token'
				value = System.getenv('CI_JOB_TOKEN')
			}
			authentication {
				//noinspection GroovyAssignabilityCheck
				header(HttpHeaderAuthentication)
			}
		}
	}
}

jar {
	setArchivesBaseName "${project.codeName}"
}

task delombok(type: DelombokTask, dependsOn: compileJava) {
	ext.outputDir = file("$buildDir/delombok")
	outputs.dir(outputDir)
	sourceSets.main.java.srcDirs.each {
		inputs.dir(it)
		args(it, '-d', outputDir)
	}
	doFirst {
		outputDir.deleteDir()
	}
}
